site_name: BioKb TaxTree
site_description: Python package to use NCBI taxonomy in the BioKB/Paean framework
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Background: background.md
  - EB/EP: ethno.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
